google-ID: 'UA-142173459-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Everything Else', path: 'menu', url: 'everything.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/squadrick'}
- {icon: 'twitter', link: 'https://twitter.com/DheerajRajaram'}
- {icon: 'envelope', link: 'mailto:dheeraj98reddy@gmail.com'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'Related posts:'

post_date_prefix: 'Written on'
